### PR TITLE
Template migration set up

### PR DESCRIPTION
**Pull request by jingwenshi-dev**
Main Changes:

- Use Pages Router file structure instead of App Dir
- Add files needed for building _app.js and _document.js

@CYH1107 @Zizizzz Please review the changes and understand the code structure. You can ignore the Netlify bot comments and checks for now, they will be fixed later (if we are going to deploy to Netlify).

### CODE REVIEW

**Comment by philipfhuang** [comment]
good merge

**Comment by Zizizzz** [comment]
Reviewed, good merge

**Comment by CYH1107** [comment]
Reviewed

**Review by CYH1107 — APPROVED** [review]
Reviewed

**Pull request merged**
